### ISSUE TITLE
Add a deprecation notice to the top of the README

### ISSUE THREAD

**Issue by jeffbyrnes** [donnemartin/saws#106]
Per #68, and specifically [this comment](https://github.com/donnemartin/saws/issues/68#issuecomment-240067034) by @donnemartin, it would seem this project is, or means to, deprecate in favor of `aws-shell`

I still see folks open issues & PRs for this, and perhaps the time has come to place a deprecation notice at the top of the README to discourage that.

**Comment by sidewinder12s** [comment]
I have been wondering if both aren't dead since aws-shell hasn't been updated in a while either.

**Comment by pol** [comment]
saws is much better than aws-shell for me.  I am unable to do variable interpolation in aws-shell (like: DOMAIN=foo aws command with --option $DOMAIN), and it also can't use loops.  It is super convenient to be able to do: for i in {1..10}; do aws command with --option thing-$i; done.   And all of the awesome consequences of patterns like that. 

So for me, aws-shell is a non-starter. Long live saws.

**Comment by AnthonyWC** [comment]
saws commit history is actually more active than aws-shell.

**Comment by jeffbyrnes** [comment]
@donnemartin care to weigh in, as its your repo?

**Comment by Braynid** [comment]
I was wondering about this as well. I see this repo is way more active than aws-shell. @donnemartin would saws be deprecated any time soon?

**Comment by jeffbyrnes** [comment]
Considering @donnemartin has made commits as recently as a week ago, I'm going to close this. We'll see what the future brings!
