### ISSUE TITLE
Improve support for piping commands

### ISSUE THREAD

**Issue by donnemartin** [donnemartin/saws#17]
Currently within `SAWS`, you can do some piping of commands such as:

    saws> aws ec2 ls > instances.txt

and view (one screen at a time) `instances.txt` within `SAWS` with:

    saws> less instances.txt

However, not all piping is supported.  For example you can't do the following:

    saws> aws ec2 ls | less

In `saws.py`, changing from:

    subprocess.call()

to

    process = pexpect.spawn()
    process.interact()

seems to allow support for this, but `pexpect` is not supported under Windows.  [`WExpect`](https://gist.github.com/anthonyeden/8488763) is dubbed as "pexpect for Windows" and might do the trick.

Thanks to krues8dr on Reddit for the suggestion.

**Comment by krues8dr** [comment]
:+1:  =D

**Comment by sesas** [comment]
:+1:

**Comment by donnemartin** [comment]
I have a fix coming up for this.  I'll also update the README.

### Executing Shell Commands

`SAWS` allows you to execute shell commands from the `saws>` prompt.

![](http://i.imgur.com/eWW8RUH.png)
