### ISSUE TITLE
Color scheme not good with white background

### ISSUE THREAD

**Issue by ldcasillas-progreso** [donnemartin/saws#18]
Light gray on white is hard to read:

![image](https://cloud.githubusercontent.com/assets/8095446/10006408/e92178be-6071-11e5-9b34-3ef9c5c309f5.png)

The documentation on the `README.md` does not mention any way of changing the color.  I tried to access the in-app documentation with the F9 key, but that's already mapped to Exposé on my OS X machine (which I might file as a separate issue).

**Comment by ldcasillas-progreso** [comment]
Using F2 to disable color did not help here—it removes the red from the `aws s3 ls` output, but still uses the light gray in the bucket name.

**Comment by donnemartin** [comment]
Thanks for the feedback, I'd like to include support for various 'themes'.  Pygments supports many of them:

http://pygments.org/docs/lexers/

Currently the theme is set to 'vim'.

**Comment by sesas** [comment]
The color scheme is not too good with a black background either: the dark blue is hard to see.

**Comment by donnemartin** [comment]
Hi Gabriel, 

Are you on Windows and see [this](https://github.com/donnemartin/saws#windows-support)?  The Windows command prompt doesn't seem to support all colors.

I'd like to try to find a better solution for Windows as well.

-Donne

**Comment by sesas** [comment]
I'm on mac w/ iTerm. 

Cheers

**Comment by donnemartin** [comment]
Gabriel, could you please attach a screenshot?  I'm also on a Mac with iTerm, but I have some terminal customizations that might be affecting what I see.

**Comment by sesas** [comment]
![image](https://cloud.githubusercontent.com/assets/554988/10014880/a2db3c86-611c-11e5-8667-2e2641c60810.png)

how's this ^

**Comment by donnemartin** [comment]
Thanks :)

**Comment by donnemartin** [comment]
I'm working on a fix to support multiple themes for syntax highlighting.  Currently, this doesn't affect output highlighting.

The theme will be set based on your [`~/.sawsrc`](https://github.com/donnemartin/saws/blob/master/saws/sawsrc) setting for the variable `theme`.

```
# Visual theme. Possible values: manni, igor, xcode, vim, autumn, vs, rrt,
# native, perldoc, borland, tango, emacs, friendly, monokai, paraiso-dark,
# colorful, murphy, bw, pastie, paraiso-light, trac, default, fruity
theme = xcode
```

Here's what it looks like on a white background with the 'xcode' theme.

![](http://i.imgur.com/tRbftWv.png)

**Comment by donnemartin** [comment]
@sesas I created a separate issue for output highlighting: https://github.com/donnemartin/saws/issues/23
