### ISSUE TITLE
Remove docs/build from the source repository.

### ISSUE THREAD

**Issue by tdi** [donnemartin/saws#66]
Hi,

Debian Maintainer here. I am working on a SAWS Debian package and I would like to be accepted into Debian as a `python-saws` package. 

Would you consider removing the prebuilt docs from the repository (`docs/build`) ? It would really make my packaging work **a lot** easier (I generate docs during packages anyways).

**Comment by donnemartin** [comment]
@tdi sounds good, thanks for the work on the SAWS Debian package!

**Comment by donnemartin** [comment]
@tdi you'll probably need a new PyPI package update?

**Comment by tdi** [comment]
@donnemartin I do not need  pypi at all, we build from sources (github), so it is important to tag every release.

**Comment by donnemartin** [comment]
@tdi sounds good, I'll reopen until I get a tagged release for you this week.

**Comment by donnemartin** [comment]
@tdi I just released [0.4.0](https://github.com/donnemartin/saws/releases/tag/0.4.0) which removes docs/build from the source repo.  Thanks in advance for the SAWS Debian package!
