### ISSUE TITLE
SAWS and AWS Collaboration

### ISSUE THREAD

**Issue by donnemartin** [donnemartin/saws#68]
## SAWS and AWS Collaboration

[SAWS](https://github.com/donnemartin/saws) and the AWS team behind [aws-cli](https://github.com/aws/aws-cli) and [boto](https://github.com/boto/boto) will be collaborating to speed up development.

[Check out the announcement and upcoming features](https://youtu.be/TnfqJYPjD9I?t=2288).  Stay tuned for more info!

## [SAWS: A Supercharged AWS CLI](https://github.com/donnemartin/saws)

![](http://i.imgur.com/vzC5zmA.gif)

[![Build Status](https://travis-ci.org/donnemartin/saws.svg?branch=master)](https://travis-ci.org/donnemartin/saws) [![Documentation Status](https://readthedocs.org/projects/saws/badge/?version=latest)](http://saws.readthedocs.org/en/latest/?badge=latest) [![Dependency Status](https://gemnasium.com/donnemartin/saws.svg)](https://gemnasium.com/donnemartin/saws) [![Codecov](https://img.shields.io/codecov/c/github/donnemartin/saws.svg)](https://codecov.io/github/donnemartin/saws/saws)

[![PyPI version](https://badge.fury.io/py/saws.svg)](http://badge.fury.io/py/saws) [![PyPI](https://img.shields.io/pypi/pyversions/saws.svg)](https://pypi.python.org/pypi/saws/) [![License](http://img.shields.io/:license-apache-blue.svg)](http://www.apache.org/licenses/LICENSE-2.0.html)

SAWS
============

### AWS CLI

Although the [AWS CLI](https://github.com/aws/aws-cli) is a great resource to manage your AWS-powered services, it's **tough to remember usage** of:

* 50+ top-level commands
* 1400+ subcommands
* Countless command-specific options
* Resources such as instance tags and buckets

### SAWS: A Supercharged AWS CLI

`SAWS` aims to **supercharge** the AWS CLI with features focusing on:

* **Improving ease-of-use**
* **Increasing productivity**

Under the hood, `SAWS` is **powered by the AWS CLI** and supports the **same commands** and **command structure**.

`SAWS` and `AWS CLI` Usage:

    aws <command> <subcommand> [parameters] [options]

`SAWS` features:

* Auto-completion of:
    * Commands
    * Subcommands
    * Options
* Auto-completion of resources:
    * Bucket names
    * Instance ids
    * Instance tags
    * [More coming soon!](https://github.com/donnemartin/saws#todo-add-more-resources)
* Customizable shortcuts
* Fuzzy completion of resources and shortcuts
* Fish-style auto-suggestions
* Syntax and output highlighting
* Execution of shell commands
* Command history
* Contextual help
* Toolbar options

`SAWS` is available for Mac, Linux, Unix, and [Windows](https://github.com/donnemartin/saws#windows-support).

![](http://i.imgur.com/Eo12q9T.png)

**Comment by DanyC97** [comment]
@donnemartin do you have any insights on when the merge will take place and maybe a beta/rc will be released?

I searched for the aws shell but couldn't find anything ...if you know/ can share that will be highly appreciated

**Comment by donnemartin** [comment]
@DanyC97 `aws-shell` is under active development, although I'm not sure we're ready to announce a release date yet.  It might be sooner than you think :)

**Comment by DanyC97** [comment]
@donnemartin okay in this case i have to wait quietly ;)

**Comment by donnemartin** [comment]
[aws-shell](https://github.com/awslabs/aws-shell) is now live!

**Comment by DanyC97** [comment]
awesome !!!!

**Comment by benkehoe** [comment]
Are SAWS and aws-shell both still under active development?

**Comment by donnemartin** [comment]
@benkehoe new feature development will be done on aws-shell.  Here's the currently active branch that will eventually be merged to master:

https://github.com/awslabs/aws-shell/tree/wizard-feature

For saws I only plan to do minor maintenance work, possibly until all saws features have been ported to aws-shell.

**Comment by sysadmiral** [comment]
So SAWS will be deprecated eventually?

**Comment by donnemartin** [comment]
@sysadmiral I think that would be the best approach.  With the AWS collaboration on [aws-shell](https://github.com/awslabs/aws-shell) we can focus on building a quality app together instead of working independently on very similar solutions.
