### ISSUE TITLE
Homebrew installation

### ISSUE THREAD

**Issue by sudhirj** [donnemartin/saws#69]
This is awesome :D For Mac users who don't use `pip` or `docker`, it would be great to have installation via [Homebrew](http://brew.sh/)

**Comment by donnemartin** [comment]
@sudhirj cool idea, thanks for the suggestion!

**Comment by zjwhitehead** [comment]
+1

**Comment by jeffbyrnes** [comment]
:+1:

**Comment by stephenrjohnson** [comment]
+1

**Comment by zanedeg** [comment]
+1

**Comment by netflash** [comment]
I think I can take it over, never did that before though :-)

@donnemartin I need some help - latest github version is 0.4.2, whilst the pip3 installs 0.4.3.
Could you please release the 0.4.3 on github too ?

**Comment by jeffbyrnes** [comment]
@netflash & everyone else here, are you aware of [`aws-shell`](https://github.com/awslabs/aws-shell)? That’s the official product, and I _think_ there was some talk of `saws` either merging in, or being deprecated by it… ah yes, #68 says pretty much that.

So maybe it would be best to focus on a Homebrew formula to install `aws-shell`, instead?

**Comment by netflash** [comment]
@jeffbyrnes interesting... I wasn't aware of pending obsoleting...

BTW `aws-shell` is already there
```
$ brew info aws-shell
aws-shell: stable 0.2.0 (bottled)
Integrated shell for working with the AWS CLI
https://github.com/awslabs/aws-shell
Not installed
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/aws-shell.rb
```

**Comment by jeffbyrnes** [comment]
@netflash so I just discovered myself! Up-to-date, too; that’s the current latest version of `aws-shell`.
