### ISSUE TITLE
Still active project?

### ISSUE THREAD

**Issue by DanyC97** [donnemartin/saws#96]
Hi @donnemartin , a while back there was a note on Readme saying saws and aws-shell efforts merge, now i see you still contributing to it.

Things changed in meantime and you reactivated the project?

**Comment by donnemartin** [comment]
Hi @DanyC97, please check out this https://github.com/donnemartin/saws/issues/68#issuecomment-240067034 for more details.

**Comment by DanyC97** [comment]
cheers @donnemartin
