### ISSUE TITLE
Are there any security risks in using the SAWS tool to access the AWS API?

### ISSUE THREAD

**Issue by ananthu99** [donnemartin/saws#98]
Hi All, 

Please let me know if there are any additional security precautions to be taken when using the SAWS tool.  I do plan to use it with the AWS IAM User Credentials.  But, I need to ensure that it's blessed by the InfoSec team - can anyone provide any additional information about it?

thanks,
Anand.

**Comment by donnemartin** [comment]
Hi @ananthu99, thanks for the question.

SAWS uses the same credentials setup as the [aws cli](https://github.com/aws/aws-cli#getting-started).  You can think of SAWS simply as a higher level wrapper around the aws cli to allow for features like autocompletion.  Commands are passed to the aws cli itself to be executed, which does the heavy lifting under the hood.
